### ISSUE TITLE
✨ feat:  추억 회고록 상세 조회 기능(닉네임 제외) 개발

### ISSUE THREAD

**Issue by thdgus0307** [MindBook-Likelion/MindBook_Backend#24]
### 페이지
- [x] PastMemoirEntity
- [x] PastMemoirResponseDto
- [x] PastMemoirRepository
- [x] PastMemoirService
- [x] PastMemoirController

**Comment by Ryeongeun-Kim** [comment]
ᓚᘏᗢ
